### ISSUE TITLE
How do I know when the modal bottom sheet is dismissed?

### ISSUE THREAD

**Issue by mddanishansari** [composablehorizons/composables-core#10]
_Not an actual issue, but in general Compose question_

So I have created custom bottom sheet which uses composable-core's `ModalBttomSheet` and I have added `onDismiss` callback to it which gets called from `LaunchedEffect` when `currentDetent` is `SheetState.Hidden`

The problem is that `onDismiss` callback is getting called even before I show the bottom sheet, obviously it will because it's in `LaunchedEffect` and `currentDetent` 's first value is `SheetState.Hidden`

**So I just wanted to ask if I want some callback like `onDimiss` or `onCollapse`, how do I achieve something like that?**  

Minimum reproducible example

```kotlin
@Composable
fun MyCustomBottomSheet(
    sheetState: ModalBottomSheetState,
    onDismiss: () -> Unit,
    content: @Composable () -> Unit
) {
    LaunchedEffect(sheetState.currentDetent) {
        if (sheetState.currentDetent == SheetDetent.Hidden) {
            onDismiss()
        }
    }

    ModalBottomSheet(state = sheetState) {
        Sheet {
            DragIndication()
            content()
        }
    }
}

@Composable
fun MyCustomBottomSheetUsage() {
    val sheetState = rememberModalBottomSheetState(initialDetent = SheetDetent.Hidden)
    Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
        Button(onClick = { sheetState.currentDetent = SheetDetent.FullyExpanded }) {
            Text(text = "Expand")
        }
    }

    MyCustomBottomSheet(
        sheetState = sheetState,
        onDismiss = {
            // This callback is getting called even if I just run the code and don't expand the bottom sheet at all
        }
    ) {
        Box(
            modifier = Modifier
                .height(500.dp),
            contentAlignment = Alignment.Center
        ) {
            Button(onClick = { sheetState.currentDetent = SheetDetent.Hidden }) {
                Text(text = "Dismiss")
            }
        }
    }
}
```

**Comment by alexstyl** [comment]
You are almost there. The state has a `isIdle` property which tells you if the sheet has stopped moving.

Try this:
```kotlin
    LaunchedEffect(state.isIdle) {
        if (state.targetDetent == SheetDetent.Hidden) {
               onDismiss()
        }
    }
```

**Comment by mddanishansari** [comment]
No @alexstyl it didn't work, still facing same issue

**Comment by alexstyl** [comment]
my bad @mddanishansari. I misunderstood what you were trying to do.

There is no built-in way to tell if the sheet has 'just' been dismissed or shown.

You would need to keep track of the last idled state manually. When the state changes to hidden and the previous was not hidden, then call your `onDismiss()` function.

**Comment by mddanishansari** [comment]
@alexstyl Here's some dirty hack but this is what worked for me

```kotlin
var isInitialRun by remember { mutableStateOf(true) }
LaunchedEffect(sheetState.currentDetent) {
	if (sheetState.isIdle && sheetState.currentDetent == SheetDetent.Hidden) {
		if (isInitialRun) {
			isInitialRun = false
		} else {
			onDismiss()
		}
	}
}
```

**Comment by mddanishansari** [comment]
Use-case is that in our app there is certain bottom sheet which has to be shown only once per session, so I need to toggle some flag once the bottom sheet is shown for the first time and then hidden.

I can toggle that flag when bottom sheet is shown but the bottom sheet appearance itself depends on that flag, so if I do that bottom sheet will appear and immediately disappear. I hope my explanation makes sense.

**Comment by alexstyl** [comment]
You can now use `ModalBottomSheet(onDismiss = {}` callback for this.

**Comment by mddanishansari** [comment]
Thank you, I can finally get rid of the workaround from my project. Will the official documentation be updated mentioned `onDismiss` feature?

**Comment by alexstyl** [comment]
The docs now mention the callback
