### ISSUE TITLE
[ModalBottomSheet] Add an option to customise system bars

### ISSUE THREAD

**Issue by strekha** [composablehorizons/composables-core#12]
The current implementation always draws dark navigation bar color (`Color.Black.copy(alpha = 0.33f`).
However, my design-system requires it to be transparent.  

Consider adding an option to customise the colors

**Comment by alexstyl** [comment]
I can consider adding an option to turn off the dimming of the nav bars. This way you can modify the system ui on your own freely.

More customization options might too much for the scope of this library.

Would that work for you?

**Comment by strekha** [comment]
Sure! Having access to a window using `DialogWindowProvider` would be a great option

**Comment by alexstyl** [comment]
wasnt aware of that. thanks for letting know. i will see what i can do

**Comment by alexstyl** [comment]
Closing this as fixed
