### ISSUE TITLE
ModalBottomSheet: Incorrect scrolling behavior when partially expanded

### ISSUE THREAD

**Issue by rst10h** [composablehorizons/composables-core#14]
**Description:**
When the `ModalBottomSheet` is partially expanded, scrolling the list upwards causes the sheet to move along with the list. The expected behavior is that the list should scroll normally within the partially expanded sheet, and the sheet should only be draggable by the header or other static elements, or when the end or beginning of the list is reached (depending on the direction of movement).

**Steps to Reproduce:**
1. Initialize a `ModalBottomSheet` with the following state:
    ```kotlin
    val partiallyExpanded = remember {
        SheetDetent(identifier = "part") { containerHeight, sheetHeight ->
            containerHeight * 0.5f
        }
    }

    val sheetState = rememberModalBottomSheetState(
        initialDetent = Hidden,
        detents = list of(Hidden, partiallyExpanded, FullyExpanded),
    )
    ```
2. Set up the initial content and the `ModalBottomSheet` as follows:
    ```kotlin
    Box(modifier = Modifier.fillMaxSize().background(Color.White), contentAlignment = Alignment.Center) {
        Text("Show ModalSheet", modifier = Modifier.padding(20.dp).clickable { sheetState.currentDetent = partiallyExpanded })
    }

    ModalBottomSheet(state = sheetState) {
        Sheet(modifier = Modifier.statusBarsPadding().displayCutoutPadding().padding(top = 20.dp)) {
            Column(modifier = Modifier.fillMaxSize().background(Color.DarkGray)) {
                Box(modifier = Modifier.fillMaxWidth()) {
                    Text("some header", modifier = Modifier.align(Alignment.Center).padding(vertical = 20.dp), color = Color.White)
                }
                LazyColumn(
                    modifier = Modifier.fillMaxSize(),
                    horizontalAlignment = Alignment.CenterHorizontally
                ) {
                    items(100) { index ->
                        Text(text = index.toString(), modifier = Modifier.padding(8.dp), color = Color.White)
                    }
                }
            }
        }
    }
    ```
3. Expand the `ModalBottomSheet` to the partially expanded state.
4. Scroll the list upwards.

**Expected Behavior:**
- The list should scroll normally within the partially expanded sheet.
- The sheet should only be draggable by the header or other static elements, or when the end or beginning of the list is reached (depending on the direction of movement).

**Actual Behavior:**
- The sheet moves along with the list when scrolling upwards.

- Library version: 1.11.0

https://github.com/user-attachments/assets/b18de698-2b47-4ae3-8d5d-a697941b63b8

**Comment by alexstyl** [comment]
Fixed in 1.11.1 https://github.com/composablehorizons/composables-core/releases/tag/1.11.1
