### ISSUE TITLE
How to handle peek bottom sheet height for different types of navigation bars?

### ISSUE THREAD

**Issue by mddanishansari** [composablehorizons/composables-core#16]
_Assumption:
Three types of navigation bar: classic 3-button navigation, gesture navigation with indicator and gesture navigation with no indicator_

I have created a new detent between `Hidden` and  `FullyExpanded`
```kotlin
val peekDetent = SheetDetent("peek") { containerHeight, sheetHeight ->
    sheetHeight * 0.585f
}
```

And this is the bottom sheet
```kotlin
@Composable
fun ExampleBottomSheet(sheetState: ModalBottomSheetState) {
    ModalBottomSheet(state = sheetState) {
        Sheet(modifier = Modifier.fillMaxWidth()) {
            val window = LocalModalWindow.current
            LaunchedEffect(Unit) {
                window.navigationBarColor = Color(0xFFDEDEDE).toArgb()
                WindowInsetsControllerCompat(window, window.decorView).isAppearanceLightNavigationBars = true
            }
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .background(Color(0xFFDEDEDE))
                    .padding(top = 16.dp)
                    .padding(horizontal = 16.dp)
                    .navigationBarsPadding()
            ) {
                Text(text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam quis varius nulla, vitae convallis purus. Nullam sagittis leo vitae augue tempor, in volutpat turpis interdum. Nunc ac diam gravida, dapibus quam lacinia, accumsan urna. Pellentesque nisi enim, volutpat eget porttitor at, tincidunt quis nisl. Curabitur fringilla fringilla pharetra. Quisque vitae tellus imperdiet, porttitor est et, efficitur dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras varius mi at sapien dictum vulputate.")
                Spacer(modifier = Modifier.height(8.dp))
                Button(modifier = Modifier.fillMaxWidth(), onClick = { /*TODO*/ }) {
                    Text(text = "Some primary button")
                }
                Spacer(modifier = Modifier.height(8.dp))
                Text(text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam quis varius nulla, vitae convallis purus. Nullam sagittis leo vitae augue tempor, in volutpat turpis interdum. Nunc ac diam gravida, dapibus quam lacinia, accumsan urna. Pellentesque nisi enim, volutpat eget porttitor at, tincidunt quis nisl. Curabitur fringilla fringilla pharetra. Quisque vitae tellus imperdiet, porttitor est et, efficitur dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras varius mi at sapien dictum vulputate.")
            }
        }
    }
}
```

The issue is that the new detent is not adjusting according to different navigation bars and it looks different in different scenario. If I adjust the `peekDetent` for gesture navigation bar then the 3-button navigation bar scenario breaks

Screenshot-1 (Perfect)
![Screenshot-1](https://github.com/user-attachments/assets/d150491d-c3d6-4a5f-a609-14d968148114)

Screenshot-2 (Some texts are visible at the bottom)
![Screenshot-2](https://github.com/user-attachments/assets/133ab5cc-08e9-4216-8e6f-1f7a2b5c68bd)

Screenshot-3 (Some texts are visible at the bottom)
![Screenshot-3](https://github.com/user-attachments/assets/55f73df2-d1be-456d-9f51-f9f078658099)

What I am doing wrong?

**Comment by alexstyl** [comment]
I am confused. what is the problem here?

what would you expect to happen that is not happening exactly?

**Comment by mddanishansari** [comment]
Sorry I shouldn't have used the word "broken", you see that in screenshot 2 and 3 at the very bottom the texts are visible. I'm not sure how to adjust the "peekDetent" so that the bottom sheet kind of anchors to the button just like in screenshot 1

**Comment by alexstyl** [comment]
The detent changes because you are setting `peek` to depend on the sheet's height. You sheet uses `navigationBarsPadding()` which changes according to the navigation bar's height. This explains why you see this change in height on every screenshot. You would either need to remove the navigationBarPadding() or change the `peek`'s height to not depend to the sheet's height.
