### ISSUE TITLE
Provide a way to change positionalThreshold & velocityThreshold in BottomSheetState

### ISSUE THREAD

**Issue by Perfomer** [composablehorizons/composables-core#20]
Hi there! 

Could you please provide a way to change `positionalThreshold` & `velocityThreshold` in `BottomSheetState`?

There is a bit annoying behavior as in Material 3 Bottom Sheets:
If you make a little swipe, then Bottom Sheet dismisses. There is many cases when you can do this accidentally. 
Bottom Sheet has a really small threshold to dismiss it. Especially it affects Bottom Sheets with scrollable content inside.

I would really like to see a fix in Composables Core.

**Comment by alexstyl** [comment]
Sounds reasonable. Let me have a look at what this means in terms of the API

**Comment by alexstyl** [comment]
Added. It will be available in the next version. I will post here when it is released.

**Comment by alexstyl** [comment]
Now available in https://github.com/composablehorizons/composables-core/releases/tag/1.13.0
