### ISSUE TITLE
BottomSheet: Click on DragIndication crash with single detent BottomSheetState

### ISSUE THREAD

**Issue by Nath-IS** [composablehorizons/composables-core#21]
**Description:**
Click on `DragIndication` crash when the `BottomSheetState` has only one detent set.

**Steps to Reproduce:**

1. Initialize a `BottomSheet` with the following state:

```
val PartiallyExpanded = remember {
    SheetDetent(identifier = "part") { containerHeight, sheetHeight ->
        containerHeight * 0.5f
    }
}

val sheetState = rememberBottomSheetState(
    initialDetent = PartiallyExpanded,
    detents = listOf(partiallyExpanded),
)
```
2. Add a `DragIndication` to the `BottomSheet` content as follows:

```
BottomSheet(state = sheetState) {
    Column(horizontalAlignment = Alignment.CenterHorizontally) {
        DragIndication(modifier = Modifier
             .padding(top = 22.dp)
             .background(Color.Black.copy(0.4f), RoundedCornerShape(100))
             .width(32.dp)
             .height(4.dp),
         )

        ...
    }
}
```

3. Click on the `DragIndication`

**Expected Behavior:**

Nothing is supposed to append, because no other detent is available.

**Actual Behavior:**

- The application crash with the following error:
```
    java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
    ...
    at com.composables.core.BottomSheetKt.DragIndication$lambda$15(BottomSheet.kt:406)
```
- Library version: 1.11.2

I know that in theory the `DragIndication` is not necessary for a BottomSheet with only one detent, because it can't be moved with a swipe, but in practice it's possible.
Is it possible to handle this case in the `onIndicationClicked` function?

**Comment by alexstyl** [comment]
Fixed. It will be available in the next version. I will post here when it is available

**Comment by alexstyl** [comment]
Now available in https://github.com/composablehorizons/composables-core/releases/tag/1.13.0
