### ISSUE TITLE
ModalBottomSheet - update to properties does not trigger recomposition

### ISSUE THREAD

**Issue by jtomli** [composablehorizons/composables-core#24]
## Issue
Updating `properties` does not trigger recomposition, since the scope is never being recreated:
`val scope = remember { ModalBottomSheetScope(state, properties, state.bottomSheetState) }` 
(ref: [ModalBottomSheet.kt#L137](https://github.com/composablehorizons/composables-core/blob/main/core/src/commonMain/kotlin/ModalBottomSheet.kt#L137 ))

## Example

    var shouldDismiss by remember { mutableStateOf(true) }

    val properties by remember(shouldDismiss) {
        mutableStateOf(
            ModalSheetProperties(
                dismissOnClickOutside = shouldDismiss,
                dismissOnBackPress = shouldDismiss,
            )
        )
    }

    ModalBottomSheet(state = sheetState, properties = properties) {
        Sheet {
            TextButton(title = "Toggle dismiss behavior") {
                shouldDismiss = !shouldDismiss
            }
        }
    }

**Expected Behavior**: the `ModalBottomSheetScope.properties` would be updated such that `dismissOnClickOutside` and `dismissOnClickOutside` would be updated to match `shouldDismiss`

**Actual Behavior**: the scope remains unchanged and both `dismissOnClickOutside` and `dismissOnClickOutside` remain `true`

## Use Case
Capture and handle back action within a bottom sheet that has a nav stack of multiple pages. (e.g. multi-step bottom sheet - 1st page can leverage default dismiss behavior (`dismissOnClickOutside` and `dismissOnClickOutside` `= true`), but subsequent pages will need to to nav back to the previous page rather than dismiss the sheet entirely (`dismissOnClickOutside` and `dismissOnClickOutside` `= false`))

**Comment by alexstyl** [comment]
That's one of the most detailed bug reports I've received. Thank you for this.

It does seem like a legit bug.

**Comment by alexstyl** [comment]
@jtomli Fixed. Will be part of the next version. I will post here when it's available

**Comment by alexstyl** [comment]
Now available in https://github.com/composablehorizons/composables-core/releases/tag/1.13.0
