### ISSUE TITLE
`FocusRingIndication.kt` uses deprecated API if `composables-core` is used with latest `compose-foundation-1.7.0-beta06`

### ISSUE THREAD

**Issue by mddanishansari** [composablehorizons/composables-core#8]
Google have deprecated `IndicationInstance` and `rememberUpdatedInstance`  which affects `FocusRingIndication` and they have suggested to move towards `IndicationNodeFactory` which uses `Modifier.Node` API

> New Features
> - Added a new Indication API, IndicationNodeFactory. This leads to more performant Indication implementations compared to the previous (now deprecated) rememberUpdatedInstance API. For migration information, see [developer.android.com](http://developer.android.com/).

Source: https://developer.android.com/jetpack/androidx/releases/compose-foundation#1.7.0-alpha01
Migration guide: https://developer.android.com/develop/ui/compose/touch-input/user-interactions/migrate-indication-ripple#migrate-indication

**Comment by alexstyl** [comment]
Given that this doesn't break anything right now, I will keep this as low priority.

However, if anyone wants to pick this up for a 1-to-1 migration to the new API, I would consider merging their PR.

**Comment by mddanishansari** [comment]
@alexstyl I can take this but the new APIs are available in new Compose Foundation version which is still in beta, so are you ok with beta version of Compose Foundation?

**Comment by alexstyl** [comment]
It depends what beta means for Compose Foundation

Can't find any info whether beta means stable for product or not.

**Comment by mddanishansari** [comment]
If we are not sure then let's wait for stable version of 1.7 or do you have any other suggestions?

**Comment by alexstyl** [comment]
Agreed. Not urgent anyhow. Closing this one.

Feel free to open a new issue if you see fit after the new APIs hit the stable release.

**Comment by alexstyl** [comment]
For the record, I implemented it by because I thought it would resolve a crash. Will merge it only when it hits stable

https://github.com/composablehorizons/composables-core/tree/indicationnodefactory
