### ISSUE TITLE
 Add a `enabled: Boolean` argument to ModalBottomSheet

### ISSUE THREAD

**Issue by mak1nt0sh** [composablehorizons/composables-core#9]
Currently there's no way to disable drag to close for ModalBottomSheet. There are pending issues but Google seems to not respond. Maybe your library would implement this?

This is especially useful for when bottom sheet contains large `LazyColumn`, as to not prematurely close the sheet on drag.

[LazyColumn unintended dismissal Issue](https://issuetracker.google.com/issues/353304855)
[Enable drag support Issue](https://issuetracker.google.com/issues/288211587)

**Comment by alexstyl** [comment]
Seems like I forgot to include it in the Modal one. the non Modal one already supports it.

Will include this on the next release

**Comment by alexstyl** [comment]
Added in https://github.com/composablehorizons/composables-core/commit/4ff5d33458001c19e10882d01132e6ec4ffabb22

Will be part of `1.10.0`
